variables:
  RELEASE_VERSION: 1.15.5

stages:
  - build
  - release

build_image_snapshot:
  stage: build
  image: docker:20.10.17
  services:
    - docker:20.10.17-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$RELEASE_VERSION"-SNAPSHOT" .
      --build-arg GITLAB_AUTH_TOKEN="$GITLAB_AUTH_TOKEN"
      --build-arg APP_NAME=Agube-dev
      --build-arg GOOGLE_MAPS_API_KEY=""
      --build-arg GOOGLE_ANALYTICS_ID=""
      --build-arg AUTH_BACKEND_API_URL="http://localhost:8000"
      --build-arg SUBSCRIPTION_BACKEND_API_URL="http://localhost:8001"
      --build-arg CONTACT_BOOK_BACKEND_API_URL="http://localhost:8002"
      --build-arg AGUBE_BACKEND_API_URL="http://localhost:8003"
    - docker tag $CI_REGISTRY_IMAGE:$RELEASE_VERSION"-SNAPSHOT" $CI_REGISTRY_IMAGE:SNAPSHOT
    - docker push $CI_REGISTRY_IMAGE:$RELEASE_VERSION"-SNAPSHOT"
    - docker push $CI_REGISTRY_IMAGE:SNAPSHOT
  only:
    - develop

build_image_release_candidate:
  stage: build
  image: docker:20.10.17
  services:
    - docker:20.10.17-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$RELEASE_VERSION"-rc" .
      --build-arg GITLAB_AUTH_TOKEN="$GITLAB_AUTH_TOKEN"
      --build-arg APP_NAME=Agube
      --build-arg GOOGLE_MAPS_API_KEY="$GOOGLE_MAPS_API_KEY"
      --build-arg GOOGLE_ANALYTICS_ID="$GOOGLE_ANALYTICS_ID"
    - docker push $CI_REGISTRY_IMAGE:$RELEASE_VERSION"-rc"
  only:
    - release

build_image_release:
  stage: build
  image: docker:20.10.17
  services:
    - docker:20.10.17-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$RELEASE_VERSION .
      --build-arg GITLAB_AUTH_TOKEN="$GITLAB_AUTH_TOKEN"
      --build-arg APP_NAME=Agube
      --build-arg GOOGLE_MAPS_API_KEY="$GOOGLE_MAPS_API_KEY"
      --build-arg GOOGLE_ANALYTICS_ID="$GOOGLE_ANALYTICS_ID"
    - docker tag $CI_REGISTRY_IMAGE:$RELEASE_VERSION $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:$RELEASE_VERSION
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - master

release_git_tag:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  variables:
    RELEASE_VERSION_SUFFIX: ""
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
      variables:
        RELEASE_VERSION_SUFFIX: "-SNAPSHOT"
    - if: $CI_COMMIT_BRANCH == "release"
      variables:
        RELEASE_VERSION_SUFFIX: "-rc"
    - if: $CI_COMMIT_BRANCH == "master"
    - if: $CI_COMMIT_TAG
      # Do not run this job when a tag is created manually
      when: never
  # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
  script:
    - echo "running release_job for $TAG"
  release:
    tag_name: $RELEASE_VERSION$RELEASE_VERSION_SUFFIX
    description: $RELEASE_VERSION$RELEASE_VERSION_SUFFIX
    ref: $CI_COMMIT_SHA