variables:
  RELEASE_VERSION: 4.16.1

stages:
  - build
  - release

build_image_snapshot:
  stage: build
  image: docker:20.10.17
  services:
    - docker:20.10.17-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$RELEASE_VERSION"-SNAPSHOT" .
      --build-arg GITLAB_AUTH_TOKEN="$GITLAB_AUTH_TOKEN"
  only:
    - develop
    - snapshot

build_image_release:
  stage: build
  image: docker:20.10.17
  services:
    - docker:20.10.17-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$RELEASE_VERSION .
      --build-arg GITLAB_AUTH_TOKEN="$GITLAB_AUTH_TOKEN"
  only:
    - master

release_git_tag:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  variables:
    RELEASE_VERSION_SUFFIX: ""
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
      variables:
        RELEASE_VERSION_SUFFIX: "-SNAPSHOT"
    - if: $CI_COMMIT_BRANCH == "master"
    - if: $CI_COMMIT_TAG
      # Do not run this job when a tag is created manually
      when: never
  # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
  script:
    - echo "running release_job for $TAG"
  release:
    tag_name: $RELEASE_VERSION$RELEASE_VERSION_SUFFIX
    description: $RELEASE_VERSION$RELEASE_VERSION_SUFFIX
    ref: $CI_COMMIT_SHA