variables:
  RELEASE_VERSION: 1.1.4

stages:
  - build
  - release

build_image_snapshot:
  stage: build
  image: docker:20.10.17
  services:
    - docker:20.10.17-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$RELEASE_VERSION"-SNAPSHOT" .
    - docker push $CI_REGISTRY_IMAGE:$RELEASE_VERSION"-SNAPSHOT"
  only:
    - snapshot

build_image_release_candidate:
  stage: build
  image: docker:20.10.17
  services:
    - docker:20.10.17-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$RELEASE_VERSION"-rc" .
    - docker push $CI_REGISTRY_IMAGE:$RELEASE_VERSION"-rc"
  only:
    - release

build_image_release:
  stage: build
  image: docker:20.10.17
  services:
    - docker:20.10.17-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$RELEASE_VERSION .
    - docker tag $CI_REGISTRY_IMAGE:$RELEASE_VERSION $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:$RELEASE_VERSION
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - master

release_git_tag:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  variables:
    RELEASE_VERSION_SUFFIX: ""
  rules:
    - if: $CI_COMMIT_BRANCH == "snapshot"
      variables:
        RELEASE_VERSION_SUFFIX: "-SNAPSHOT"
    - if: $CI_COMMIT_BRANCH == "release"
      variables:
        RELEASE_VERSION_SUFFIX: "-rc"
    - if: $CI_COMMIT_BRANCH == "master"
    - if: $CI_COMMIT_TAG
      # Do not run this job when a tag is created manually
      when: never
  # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
  script:
    - echo "running release_job for $TAG"
  release:
    tag_name: $RELEASE_VERSION$RELEASE_VERSION_SUFFIX
    description: $RELEASE_VERSION$RELEASE_VERSION_SUFFIX
    ref: $CI_COMMIT_SHA