docker-build-develop:
  image: docker:latest
  # stage: .post
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!, running $CI_COMMIT_BRANCH"
    - echo "Create image docker -> agube-backend from the $CI_COMMIT_BRANCH branch."
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - gitlab-ci
