stages:
    - build

docker_build:
    image: docker:latest
    stage: build
    services:
        - docker:dind
    before_script:
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    script:
        - docker build --pull -t "$CI_REGISTRY_IMAGE":latest . --build-arg GITLAB_AUTH_TOKEN="$GITLAB_AUTH_TOKEN"
        - docker tag "$CI_REGISTRY_IMAGE":latest "$CI_REGISTRY_IMAGE":1.4.0
        - docker push "$CI_REGISTRY_IMAGE":1.4.0
        - docker push "$CI_REGISTRY_IMAGE":latest
    only:
        - gitlab-ci