version: "3.8"

services:
  # Postgres Database
  db:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - ./docker/prod/.env.db.prod
    networks:
      - backend

  # RabbitMQ - queue
  rabbitmq:
    hostname: rabbit
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      # here, we can access rabbitmq management plugin
      - 15672:15672
    env_file:
      - ./docker/prod/.env.rabbit.prod
    networks:
      - backend

  # Django Backend server
  subscription-backend:
    image: registry.gitlab.com/availa/proyectos/subscription/backend/subscription-be
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/availa
    env_file:
      - ./docker/prod/.env.be.prod
    depends_on:
      - db
      - rabbitmq
    networks:
      - backend
  contact-book-backend:
    image: registry.gitlab.com/availa/proyectos/contact-book/backend/contact-book-be
    command: python manage.py runserver 0.0.0.0:8001
    ports:
      - 8001:8001
    volumes:
      - .:/availa
    env_file:
      - ./docker/prod/.env.be.prod
    depends_on:
      - db
      - rabbitmq
    networks:
      - backend
  agube-backend:
    image: registry.gitlab.com/availa/proyectos/agube/backend/agube-be
    command: python manage.py runserver 0.0.0.0:8002
    ports:
      - 8002:8002
    volumes:
      - .:/availa
    env_file:
      - ./docker/prod/.env.be.prod
    depends_on:
      - db
      - rabbitmq
      - subscription-backend
      - contact-book-backend
    networks:
      - backend

networks:
  backend:
    driver: bridge