version: "3.8"

services:
  # Postgres Database
  db:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - ./docker/dev/.env.db.dev
    networks:
      - backend

  # RabbitMQ - queue
  rabbitmq:
    hostname: rabbit
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      # here, we can access rabbitmq management plugin
      - 15672:15672
    env_file:
      - ./docker/dev/.env.rabbit.dev
    networks:
      - backend

  # Django Backend server
  auth-backend:
    hostname: auth-backend
    image: registry.gitlab.com/availa/proyectos/auth/backend/auth-be
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/availa
    env_file:
      - ./docker/dev/.env.be.dev
    depends_on:
      - db
      - rabbitmq
    networks:
      - backend
  subscription-backend:
    hostname: subscription-backend
    image: registry.gitlab.com/availa/proyectos/subscription/backend/subscription-be
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8001:8000
    volumes:
      - .:/availa
    env_file:
      - ./docker/dev/.env.be.dev
    depends_on:
      - db
      - rabbitmq
    networks:
      - backend
  contact-book-backend:
    hostname: contact-book-backend
    image: registry.gitlab.com/availa/proyectos/contact-book/backend/contact-book-be
    # build: E:\git\Availa\proyectos\contact-book\backend\contact-book-be
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8002:8000
    volumes:
      - .:/availa
    env_file:
      - ./docker/dev/.env.be.dev
    depends_on:
      - db
      - rabbitmq
    networks:
      - backend
  agube-backend:
    hostname: agube-backend
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8003:8000
      - 5555:5555
    volumes:
      - .:/availa-agube
    env_file:
      - ./docker/dev/.env.be.dev
    depends_on:
      - db
      - rabbitmq
    networks:
      - backend

networks:
  backend:
    driver: bridge