version: "3.9"
services:
  # Frontend service
  agube-env-fe:
    container_name: test-fe
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: Agube
        GOOGLE_MAPS_API_KEY:
        GOOGLE_ANALYTICS_ID:
        AUTH_BACKEND_API_URL: http://localhost:30004
        SUBSCRIPTION_BACKEND_API_URL: http://localhost:30001
        CONTACT_BOOK_BACKEND_API_URL: http://localhost:30002
        AGUBE_BACKEND_API_URL: http://localhost:30003
    command: nginx -g 'daemon off;'
    ports:
      - 8080:8080