version: "3.8"

services:
  # Postgres DB
  db:
    container_name: postgres-db
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - ./docker/dev/.env.db.dev
    networks:
      - backend

  # RabbitMQ
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbit
    image: rabbitmq:3.8-management
    ports:
      - 5672:5672
      # here, we can access rabbitmq management plugin
      - 15672:15672
    env_file:
      - ./docker/dev/.env.rabbit.dev
    networks:
      - backend

  # BE: agube
  agube-backend:
    container_name: agube-backend
    hostname: agube-backend
    image: registry.gitlab.com/availa/proyectos/agube/backend/agube-be
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8003:8000
      - 5555:5555
    environment:
      - DJANGO_SECRET_KEY=$DEV_DJANGO_SECRET_KEY
      - EMAIL_HOST=smtp.googlemail.com
      - EMAIL_PORT=587
      - EMAIL_HOST_USER=$DEV_USER_MAIL
      - EMAIL_HOST_PASSWORD=$DEV_USER_MAIL_PASSWORD
    volumes:
      - .:/availa
    env_file:
      - ./docker/dev/.env.be.dev
    depends_on:
      - db
      - rabbitmq
    networks:
      - backend

  # BE: auth
  auth-backend:
    container_name: auth-backend
    hostname: auth-backend
    image: registry.gitlab.com/availa/proyectos/auth/backend/auth-be
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/availa
    env_file:
      - ./docker/dev/.env.be.dev
    depends_on:
      - db
      - rabbitmq
    networks:
      - backend

  # BE: contact-book
  contact-book-backend:
    container_name: contact-book-backend
    hostname: contact-book-backend
    image: registry.gitlab.com/availa/proyectos/contact-book/backend/contact-book-be
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8002:8000
    environment:
      - DJANGO_SECRET_KEY=$DEV_DJANGO_SECRET_KEY
    volumes:
      - .:/availa
    env_file:
      - ./docker/dev/.env.be.dev
    depends_on:
      - db
      - rabbitmq
    networks:
      - backend

  # BE: subscription
  subscription-backend:
    container_name: subscription-backend
    hostname: subscription-backend
    image: registry.gitlab.com/availa/proyectos/subscription/backend/subscription-be
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8001:8000
    environment:
      - DJANGO_SECRET_KEY=$DEV_DJANGO_SECRET_KEY
      - EMAIL_HOST=smtp.googlemail.com
      - EMAIL_PORT=587
      - EMAIL_HOST_USER=$DEV_USER_MAIL
      - EMAIL_HOST_PASSWORD=$DEV_USER_MAIL_PASSWORD
      - REDIRECT_TO=localhost:8080/enable-account?id=
    volumes:
      - .:/availa
    env_file:
      - ./docker/dev/.env.be.dev
    depends_on:
      - db
      - rabbitmq
    networks:
      - backend

  # BE: task
  task-backend:
    container_name: task-backend
    hostname: task-backend
    image: registry.gitlab.com/availa/proyectos/task/backend/task-be
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8004:8000
    volumes:
      - .:/availa
    env_file:
      - ./docker/dev/.env.be.dev
    depends_on:
      - db
      - rabbitmq
    networks:
      - backend

networks:
  backend:
    driver: bridge
