version: "3.8"

services:
  agube-be:
    hostname: agube-be
    build:
      context: ../.
      dockerfile: Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - 8003:8000
      - 5555:5555
    volumes:
      - ../.:/availa-agube
    environment:
      - DJANGO_SECRET_KEY=$DEV_DJANGO_SECRET_KEY
      - EMAIL_HOST=smtp.googlemail.com
      - EMAIL_PORT=587
      - EMAIL_HOST_USER=$DEV_USER_MAIL
      - EMAIL_HOST_PASSWORD=$DEV_USER_MAIL_PASSWORD
    env_file:
      - .env.be
    networks:
      - backend

networks:
  backend:
    driver: bridge