# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish Api Package

on:
  push:
    tags:
      - "*"

jobs:
  build_and_publish:
    name: Build and Publish Api if does not exist before
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        working-directory: ./api
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/

      - name: npm dependencies
        run: |
          npm config set @availaoss:registry https://npm.pkg.github.com/
          npm config set //npm.pkg.github.com/:_authToken ${{ secrets.AGUBE_AUTH_SECRET }}
          npm install

      - name: publish
        run: |
          npm run package-publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.AGUBE_AUTH_SECRET }}
